name: Release
on:
  push:
    branches:
      - master
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+.x'
jobs:
  release:
    name: Release
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          persist-credentials: false
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
      - name: Semantic Release
        uses: BrightspaceUI/actions/semantic-release@master
        with:
          GITHUB_TOKEN: ${{ secrets.D2L_GITHUB_TOKEN }}
